"""P6.6 Strategy Research & Simulation Lab contracts."""

from .backtest import (
    BacktestConfiguration,
    ResearchPreview,
    preview_backtest,
    run_historical_backtest,
    run_panel_backtest,
)
from .compiler import CompiledStrategy, StrategyCompiler, compile_strategy, strategy_ir
from .diagnostics import (
    BacktestPaperComparison,
    FeatureDriftReport,
    compare_backtest_paper,
    compute_feature_drift,
    feature_drift,
)
from .education import (
    CodeSafetyReport,
    EducationalCode,
    StrategyLearningTrace,
    generate_educational_code,
    learning_cards,
    scan_educational_code,
    validate_generated_code,
)
from .export import ResearchPackage, ResearchPackageExporter, export_research_package
from .features import (
    FeatureRegistry,
    PointInTimeViolation,
    assert_point_in_time,
    builtin_feature_registry,
    feature_graph_for_template,
)
from .lab import LabRun, StrategyLab, StrategyResearchLab
from .learning import StrategyLearningBundle, strategy_learning_bundle
from .models import (
    FeatureDefinition,
    FeatureGraph,
    FeatureNode,
    FeatureVersion,
    StrategyIR,
    StrategyIRNode,
    StrategyReview,
    StrategySpec,
    StrategyVersion,
)
from .paper import (
    PaperRun,
    PaperSignal,
    PaperSimulator,
    VirtualFill,
    VirtualOrder,
    VirtualPortfolio,
    run_paper,
)
from .strategy import StrategyInterpreter, review_strategy
from .validation import (
    MultipleTestingSummary,
    WalkForwardReport,
    WalkForwardWindow,
    evaluate_frozen_oos,
    make_oos_plan,
    walk_forward,
)
from .workbench import (
    ALLOWED_FAULT_ACTIONS,
    ALLOWED_RISK_ACTIONS,
    POSITION_MAPPINGS,
    RISK_STATES,
    ExecutionPolicy,
    FaultPolicy,
    ParameterChangeExplanation,
    PolicyProposal,
    PositionPolicySpec,
    ResearchCharter,
    RiskStatePolicy,
)
from .workbench_engine import WorkbenchPoint, WorkbenchRun, run_workbench, transition_risk
from .workbench_explanations import build_explanation_package
from .workbench_research import (
    FactorGraphSpec,
    ResearchAttempt,
    ResearchSession,
    WorkbenchStore,
    evaluate_factor_graph,
)

__all__ = [
    "ALLOWED_FAULT_ACTIONS",
    "ALLOWED_RISK_ACTIONS",
    "POSITION_MAPPINGS",
    "RISK_STATES",
    "BacktestConfiguration",
    "BacktestPaperComparison",
    "CodeSafetyReport",
    "CompiledStrategy",
    "EducationalCode",
    "ExecutionPolicy",
    "FactorGraphSpec",
    "FaultPolicy",
    "FeatureDefinition",
    "FeatureDriftReport",
    "FeatureGraph",
    "FeatureNode",
    "FeatureRegistry",
    "FeatureVersion",
    "LabRun",
    "MultipleTestingSummary",
    "PaperRun",
    "PaperSignal",
    "PaperSimulator",
    "ParameterChangeExplanation",
    "PointInTimeViolation",
    "PolicyProposal",
    "PositionPolicySpec",
    "ResearchAttempt",
    "ResearchCharter",
    "ResearchPackage",
    "ResearchPackageExporter",
    "ResearchPreview",
    "ResearchSession",
    "RiskStatePolicy",
    "StrategyCompiler",
    "StrategyIR",
    "StrategyIRNode",
    "StrategyInterpreter",
    "StrategyLab",
    "StrategyLearningBundle",
    "StrategyLearningTrace",
    "StrategyResearchLab",
    "StrategyReview",
    "StrategySpec",
    "StrategyVersion",
    "VirtualFill",
    "VirtualOrder",
    "VirtualPortfolio",
    "WalkForwardReport",
    "WalkForwardWindow",
    "WorkbenchPoint",
    "WorkbenchRun",
    "WorkbenchStore",
    "assert_point_in_time",
    "build_explanation_package",
    "builtin_feature_registry",
    "compare_backtest_paper",
    "compile_strategy",
    "compute_feature_drift",
    "evaluate_factor_graph",
    "evaluate_frozen_oos",
    "export_research_package",
    "feature_drift",
    "feature_graph_for_template",
    "generate_educational_code",
    "learning_cards",
    "make_oos_plan",
    "preview_backtest",
    "review_strategy",
    "run_historical_backtest",
    "run_panel_backtest",
    "run_paper",
    "run_workbench",
    "scan_educational_code",
    "strategy_ir",
    "strategy_learning_bundle",
    "transition_risk",
    "validate_generated_code",
    "walk_forward",
]
