"""Governed, offline-first research-agent contracts and orchestration hooks."""

from finahinking.factors.registry import (
    FactorHealth,
    FactorHealthStatus,
    FactorMetadata,
    FactorRegistry,
)

from .contracts import (
    AgentReport,
    CheckpointIdentity,
    DecisionCard,
    FailureKind,
    ProviderSelection,
    ReportManifest,
    ResearchPlan,
    ResearchRequest,
    ResearchRunResult,
    ResearchRunState,
    ResearchState,
    RiskReview,
    RunEvent,
    stable_digest,
    to_jsonable,
    validate_transition,
)
from .drivers import CodexInteractiveDriver, CompatibleApiDriver, OfflineDriver, UserApiDriver
from .factor_loop import (
    FactorResearchRound,
    FactorResearchRun,
    FactorResearchState,
    run_factor_research,
)
from .learning import LearningEntry, LearningStore, reconcile_learning, validate_learning_entry
from .provider_status import ProviderCredentialRef, ProviderStatus, provider_status_payload
from .reports import (
    BundleVerification,
    ReportBundleWriter,
    compare_report_manifests,
    render_section_html,
    verify_report_bundle,
)
from .run_store import (
    CheckpointCorruptError,
    CheckpointIdentityMismatch,
    CheckpointIncompatibleError,
    CheckpointRecord,
    CheckpointRestoreError,
    CheckpointSchemaError,
    CheckpointValidationError,
    CompletedRunError,
    CorruptCheckpointError,
    ResearchRunStore,
    RunControl,
    RunStoreError,
)
from .tools import (
    ResearchToolGateway,
    ResearchToolName,
    ResearchToolRequest,
    ResearchToolResponse,
    ResearchToolStatus,
)
from .workflow import AnalystSpec, ResearchOrchestrator, WorkflowLimits

__all__ = [
    "AgentReport",
    "AnalystSpec",
    "BundleVerification",
    "CheckpointCorruptError",
    "CheckpointIdentity",
    "CheckpointIdentityMismatch",
    "CheckpointIncompatibleError",
    "CheckpointRecord",
    "CheckpointRestoreError",
    "CheckpointSchemaError",
    "CheckpointValidationError",
    "CodexInteractiveDriver",
    "CompatibleApiDriver",
    "CompletedRunError",
    "CorruptCheckpointError",
    "DecisionCard",
    "FactorHealth",
    "FactorHealthStatus",
    "FactorMetadata",
    "FactorRegistry",
    "FactorResearchRound",
    "FactorResearchRun",
    "FactorResearchState",
    "FailureKind",
    "LearningEntry",
    "LearningStore",
    "OfflineDriver",
    "ProviderCredentialRef",
    "ProviderSelection",
    "ProviderStatus",
    "ReportBundleWriter",
    "ReportManifest",
    "ResearchOrchestrator",
    "ResearchPlan",
    "ResearchRequest",
    "ResearchRunResult",
    "ResearchRunState",
    "ResearchRunStore",
    "ResearchState",
    "ResearchToolGateway",
    "ResearchToolName",
    "ResearchToolRequest",
    "ResearchToolResponse",
    "ResearchToolStatus",
    "RiskReview",
    "RunControl",
    "RunEvent",
    "RunStoreError",
    "UserApiDriver",
    "WorkflowLimits",
    "compare_report_manifests",
    "provider_status_payload",
    "reconcile_learning",
    "render_section_html",
    "run_factor_research",
    "stable_digest",
    "to_jsonable",
    "validate_learning_entry",
    "validate_transition",
    "verify_report_bundle",
]
