"""Governed, offline-first research-agent contracts and orchestration hooks."""

from finahinking.factors.registry import (
    FactorHealth,
    FactorHealthStatus,
    FactorMetadata,
    FactorRegistry,
)

from .agent_roles import AgentRuntime, AgentStatus, RoleCapabilityPolicy
from .codex_bridge import CodexBridge, CodexDispatchRecord, CodexTaskEnvelope
from .contracts import (
    AgentOutcome,
    AgentReport,
    AgentRole,
    AgentTask,
    CheckpointIdentity,
    DecisionCard,
    FailureKind,
    ProviderSelection,
    ReportManifest,
    ResearchPlan,
    ResearchRequest,
    ResearchRunResult,
    ResearchRunState,
    ResearchState,
    RiskReview,
    RunEvent,
    stable_digest,
    to_jsonable,
    validate_transition,
)
from .drivers import CodexInteractiveDriver, CompatibleApiDriver, OfflineDriver, UserApiDriver
from .factor_catalog_loader import (
    BUILTIN_AUDITED_CATALOG,
    DEFAULT_FACTOR_CATALOG,
    CatalogAdmissionProposal,
    admit_catalog_entry,
    load_audited_catalog,
)
from .factor_experiments import (
    FactorExperimentRecord,
    FactorExperimentResult,
    FactorExperimentSpec,
    run_factor_experiments,
)
from .factor_loop import (
    FactorResearchRound,
    FactorResearchRun,
    FactorResearchState,
    run_factor_research,
)
from .job_queue import JobQueue, JobRecord, JobStatus, StaleLeaseError
from .learning import LearningEntry, LearningStore, reconcile_learning, validate_learning_entry
from .learning_manager import (
    AdmissionDecision,
    AdmittedUpdate,
    LearningAdmissionRecord,
    LearningApplyPreview,
    LearningManager,
    LearningProposalRecord,
    LearningProposalStore,
    LearningUpdateProposal,
    LearningUpdateStatus,
    VersionedResearchPolicy,
)
from .observability import (
    RuntimeBudget,
    RuntimeLimitExceeded,
    RuntimeMetrics,
    bind_runtime_budget,
    current_runtime_budget,
)
from .paper_trader import PaperLedger, PaperLedgerEntry, PaperTrader
from .portfolio_runtime import PaperPortfolioProposal, PortfolioManager
from .provider_adapters import (
    DeepSeekCompatibleAdapter,
    OpenAICompatibleAdapter,
    ProviderAdapterError,
    ProviderContractResult,
    ProviderFailureKind,
    RetryPolicy,
    build_opt_in_provider_adapter,
)
from .provider_status import ProviderCredentialRef, ProviderStatus, provider_status_payload
from .quant_analytics import (
    ParameterSurface,
    PerformanceReport,
    compute_parameter_surface,
    compute_performance_report,
)
from .reports import (
    BundleVerification,
    ReportBundleWriter,
    compare_experiments,
    compare_report_manifests,
    render_section_html,
    verify_report_bundle,
)
from .risk_runtime import ExposureReport, RiskManager, RiskReviewResult, StressReport
from .run_store import (
    CheckpointCorruptError,
    CheckpointIdentityMismatch,
    CheckpointIncompatibleError,
    CheckpointRecord,
    CheckpointRestoreError,
    CheckpointSchemaError,
    CheckpointValidationError,
    CompletedRunError,
    CorruptCheckpointError,
    ResearchRunStore,
    RunControl,
    RunStoreError,
)
from .runtime_protocol import (
    ALLOWED_MESSAGE_KINDS,
    ProtocolError,
    WorkerInvocation,
    WorkerMessage,
    decode_message,
    encode_message,
)
from .runtime_service import ResearchRuntimeService, RuntimeLimits
from .settlement import SettlementEvent
from .stage_registry import (
    StageRegistry,
    StageRegistryError,
    StageRunner,
    StageSpec,
    default_stage_registry,
    run_default_workflow_stage,
)
from .tools import (
    ResearchToolGateway,
    ResearchToolName,
    ResearchToolRequest,
    ResearchToolResponse,
    ResearchToolStatus,
)
from .ui import register_runtime_snapshot, research_runtime_view_model
from .worker import ResearchWorker, WorkerResult, WorkerStatus
from .workflow import AnalystSpec, ResearchOrchestrator, WorkflowLimits

__all__ = [
    "ALLOWED_MESSAGE_KINDS",
    "BUILTIN_AUDITED_CATALOG",
    "DEFAULT_FACTOR_CATALOG",
    "AdmissionDecision",
    "AdmittedUpdate",
    "AgentOutcome",
    "AgentReport",
    "AgentRole",
    "AgentRuntime",
    "AgentStatus",
    "AgentTask",
    "AnalystSpec",
    "BundleVerification",
    "CatalogAdmissionProposal",
    "CheckpointCorruptError",
    "CheckpointIdentity",
    "CheckpointIdentityMismatch",
    "CheckpointIncompatibleError",
    "CheckpointRecord",
    "CheckpointRestoreError",
    "CheckpointSchemaError",
    "CheckpointValidationError",
    "CodexBridge",
    "CodexDispatchRecord",
    "CodexInteractiveDriver",
    "CodexTaskEnvelope",
    "CompatibleApiDriver",
    "CompletedRunError",
    "CorruptCheckpointError",
    "DecisionCard",
    "DeepSeekCompatibleAdapter",
    "ExposureReport",
    "FactorExperimentRecord",
    "FactorExperimentResult",
    "FactorExperimentSpec",
    "FactorHealth",
    "FactorHealthStatus",
    "FactorMetadata",
    "FactorRegistry",
    "FactorResearchRound",
    "FactorResearchRun",
    "FactorResearchState",
    "FailureKind",
    "JobQueue",
    "JobRecord",
    "JobStatus",
    "LearningAdmissionRecord",
    "LearningApplyPreview",
    "LearningEntry",
    "LearningManager",
    "LearningProposalRecord",
    "LearningProposalStore",
    "LearningStore",
    "LearningUpdateProposal",
    "LearningUpdateStatus",
    "OfflineDriver",
    "OpenAICompatibleAdapter",
    "PaperLedger",
    "PaperLedgerEntry",
    "PaperPortfolioProposal",
    "PaperTrader",
    "ParameterSurface",
    "PerformanceReport",
    "PortfolioManager",
    "ProtocolError",
    "ProviderAdapterError",
    "ProviderContractResult",
    "ProviderCredentialRef",
    "ProviderFailureKind",
    "ProviderSelection",
    "ProviderStatus",
    "ReportBundleWriter",
    "ReportManifest",
    "ResearchOrchestrator",
    "ResearchPlan",
    "ResearchRequest",
    "ResearchRunResult",
    "ResearchRunState",
    "ResearchRunStore",
    "ResearchRuntimeService",
    "ResearchState",
    "ResearchToolGateway",
    "ResearchToolName",
    "ResearchToolRequest",
    "ResearchToolResponse",
    "ResearchToolStatus",
    "ResearchWorker",
    "RetryPolicy",
    "RiskManager",
    "RiskReview",
    "RiskReviewResult",
    "RoleCapabilityPolicy",
    "RunControl",
    "RunEvent",
    "RunStoreError",
    "RuntimeBudget",
    "RuntimeLimitExceeded",
    "RuntimeLimits",
    "RuntimeMetrics",
    "SettlementEvent",
    "StageRegistry",
    "StageRegistryError",
    "StageRunner",
    "StageSpec",
    "StaleLeaseError",
    "StressReport",
    "UserApiDriver",
    "VersionedResearchPolicy",
    "WorkerInvocation",
    "WorkerMessage",
    "WorkerResult",
    "WorkerStatus",
    "WorkflowLimits",
    "admit_catalog_entry",
    "bind_runtime_budget",
    "build_opt_in_provider_adapter",
    "compare_experiments",
    "compare_report_manifests",
    "compute_parameter_surface",
    "compute_performance_report",
    "current_runtime_budget",
    "decode_message",
    "default_stage_registry",
    "encode_message",
    "load_audited_catalog",
    "provider_status_payload",
    "reconcile_learning",
    "register_runtime_snapshot",
    "render_section_html",
    "research_runtime_view_model",
    "run_default_workflow_stage",
    "run_factor_experiments",
    "run_factor_research",
    "stable_digest",
    "to_jsonable",
    "validate_learning_entry",
    "validate_transition",
    "verify_report_bundle",
]
