"""Backend-neutral run-store contract."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class RunStoreProtocol(Protocol):
    root: Path

    def run_dir(self, run_id: str) -> Path: ...
    def read_json(self, run_id: str, filename: str) -> dict[str, Any]: ...

    def create(self, task: str, mode: str, output_level: str, request: dict[str, Any] | None = None, run_id: str | None = None, **metadata: Any) -> str: ...
    def create_with_result(self, task: str, mode: str, output_level: str, request: dict[str, Any] | None = None, run_id: str | None = None, **metadata: Any) -> dict[str, Any]: ...
    def get(self, run_id: str) -> dict[str, Any]: ...
    def status(self, run_id: str) -> dict[str, Any]: ...
    def request(self, run_id: str) -> dict[str, Any]: ...
    def update_status(self, run_id: str, **fields: Any) -> dict[str, Any]: ...
    def save_contract(self, run_id: str, contract: dict[str, Any]) -> None: ...
    def save_plan(self, run_id: str, plan: dict[str, Any]) -> None: ...
    def save_execution(self, run_id: str, execution: dict[str, Any], attempt: int | None = None) -> None: ...
    def save_checkpoint(self, run_id: str, checkpoint: dict[str, Any]) -> Path: ...
    def load_checkpoint(self, run_id: str) -> dict[str, Any] | None: ...
    def register_artifacts(self, run_id: str, artifacts: list[Any] | None = None) -> list[dict[str, Any]]: ...
    def artifact(self, run_id: str, name: str, include_content: bool = True) -> dict[str, Any]: ...
    def acquire_lease(self, run_id: str, worker_id: str, ttl_seconds: int = 300) -> dict[str, Any]: ...
    def heartbeat_lease(self, run_id: str, worker_id: str, ttl_seconds: int = 300) -> dict[str, Any]: ...
    def release_lease(self, run_id: str, worker_id: str, status: str | None = None) -> dict[str, Any]: ...
    def recover_stale_runs(self) -> list[str]: ...
    def cancel(self, run_id: str) -> dict[str, Any]: ...
    def authorize(self, run_id: str, client_id: str | None = None, owner_id: str | None = None, tenant_id: str | None = None, admin: bool = False) -> bool: ...
    def list_runs(self, **filters: Any) -> dict[str, Any]: ...
